### ISSUE TITLE
Weird HTML structure in MultiView Tabbar with icons sample

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#204]
At http://docs.webix.com/samples/20_multiview/05_tabbar_with_icons.html there's this HTML:

```html
<div class="header_comment">Tabbar and Multiview</div>
        <div class="header_comment">Tabview</div>
        <div style="clear:both;"><div>
		<div id="areaA"></div>
```

Probably the `<div>` after the clear div should be a closing `</div>`. Right now we have divs out of body:

![image](https://cloud.githubusercontent.com/assets/33569/5973890/7c4a4d18-a822-11e4-8d51-793c4896a886.png)

**Comment by Zwillinge** [comment]
Fixed.

**Comment by dandv** [comment]
I still see the same source code at http://docs.webix.com/samples/20_multiview/05_tabbar_with_icons.html
