### ISSUE TITLE
Keyboard on Android (Chrome) overlaps form fields

### ISSUE THREAD

**Issue by Tystar** [webix-hub/tracker#258]
I'm writing a very simple mobile app in webix. It's a simple form with 3 fields, 1 text 2 textarea.

When i reach the third textarea, the android keyboard pops up like always, but overlaps the textarea, the form (or page) don't scroll up to adapt the page and see the textarea and the keyboard at same time, so you can't see what you're writing.

http://webix.com/snippet/d0a31b45

When i try to write in field "Descripcion" u see what i mean. 

It only happens using Chrome (47.0.2526.83). In Firefox for Android it works as expected. The problem is Apache Cordova use Chrome and the issue happens there.

**Comment by Tystar** [comment]
It doesn't have been fixed!

**Comment by Maria-Staskova** [comment]
Sorry. You are correct. The overlap issue is still there. Webix sets overflow: hidden for document body. We can not remove this css from our library. But you can try to apply the following in your application:

if(webix.env.touch)
  document.body.style.overflowY = "auto";
